language: rust
sudo: false
cache: cargo

rust:
  - stable
script:
  - cargo build --verbose --release --workspace --manifest-path src/Cargo.toml



matrix:
  # Performance tweak
  fast_finish: true

  include:
    # Linux
    #- env: TARGET=x86_64-unknown-linux-musl

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx
    #- env: TARGET=aarch64-apple-darwin
    #  os: osx
      
    # Windows
    #- env: TARGET=x86_64-pc-windows-gnu

deploy:
  - provider: releases
    skip_cleanup: true
    edge: true
    on:
      tags: true
      #condition: "$TRAVIS_RUST_VERSION = stable"
      #branch: master
    file: target/release/dclias
    api_key:
      secure: "SS7JjkDvqzlQ5Dwhg0/vFeP+c19L0cX8WDmJHGnXiF7TctTuAzMR8AKXb8csgShKVA8gvsX53gf3gbjV49N7ZwLZYmA5r0Sow8QqvRyY2/BrYXmbySXUldXa26gdtn2wLtl6BhmybxrVHFUt4MHgMtTv8YfEhn23jQXJcW18ee8aZ7Rbffn9nIYvtRoHQVbRQ4qrCtDw9M3Ht7m45f4M5fP217KW1wImbza2jqJLc/hDtOly//gtlvToVDmC7etTjLKkWTOiGcGgpkh6Y4w2FPIofEXVuo3DWAK7lz4RFzRxqWWuTMvTY0UzyNMtCuYGY/ALT4t945bX22lVeaIpCJ+m11d4fclm4qkp9bfegIOboGw013XAaHF34Lvt/7EaAihcbFuJgEJO0De31wS1Vhc7glMJc8purXTiKA6LEHdqXsEfrcThIN/IvI8VZYDuz/55Z+h9aY7relnQHgmr/z2/mTnVu72UZ+aFMmcWJuPo/0DImb+Bh/u60pI79x1CoHMg5q4kX+QNJ7x1arh9eM3LNkb9iXcSfJvv/jXw0mSOssr+Z/Bst5v0trd1BYuiCJ7Uh6DKX0bZSlVsNlhLxdOcItnT9s25fxhBrV2t4tjzh81gTqGD8sMTI7uMMIFuePe7E4ULHGCAiW4Q+VXaacJ6MRnTZapk12AZyLmYMP8="