name: dcli

on: [push]

jobs:

  build-arm-linux-musl:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Config
        id: config
        run: |
            echo ::set-output name=SOURCE_TAG::${GITHUB_REF/refs\/tags\//}
            echo ::set-output name=TARGET_NAME::arm-unknown-linux-musleabi
      - uses: actions/checkout@master
      - name: Build
        uses: stevenleadbeater/rust-musl-builder@master
        with:
          args: /bin/bash -c "export DESTINY_API_KEY=${{ secrets.DESTINY_API_KEY }} && rustup update && cargo build --manifest-path=src/Cargo.toml --release --target=arm-unknown-linux-musleabi"
      - name: Process and Package
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        env:
          SOURCE_TAG: ${{ steps.config.outputs.SOURCE_TAG }}
          TARGET_NAME: ${{ steps.config.outputs.TARGET_NAME }}
        run: echo SOURCE_TAG ${SOURCE_TAG} && cp src/target/${TARGET_NAME}/release/dclia . && strip dclia && cp src/target/${TARGET_NAME}/release/dclic . && strip dclic  && cp src/target/${TARGET_NAME}/release/dclics . && strip dclics && cp src/target/${TARGET_NAME}/release/dclims . && strip dclims && cp src/target/${TARGET_NAME}/release/dclim . && strip dclim && cp src/target/${TARGET_NAME}/release/dclis . && strip dclis && cp src/target/${TARGET_NAME}/release/dclitime . && strip dclitime && cp src/target/${TARGET_NAME}/release/dcliah . && strip dcliah && cp src/target/${TARGET_NAME}/release/dclias . && strip dclias && zip -j dcli_${TARGET_NAME}_${SOURCE_TAG}.zip RELEASE.md README.md LICENSE.md dclia dclic dclics dclims dclim dclis dclitime dcliah dclias
        
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dcli_${{ steps.config.outputs.TARGET_NAME }}_${{ steps.config.outputs.SOURCE_TAG }}.zip
            RELEASE.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux-musl:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Config
        id: config
        run: |
            echo ::set-output name=SOURCE_TAG::${GITHUB_REF/refs\/tags\//}
            echo ::set-output name=TARGET_NAME::x86_64-unknown-linux-musl
      - uses: actions/checkout@master
      - name: Build
        uses: stevenleadbeater/rust-musl-builder@master
        with:
          args: /bin/bash -c "export DESTINY_API_KEY=${{ secrets.DESTINY_API_KEY }} && rustup update && cargo build --manifest-path=src/Cargo.toml --release --target=x86_64-unknown-linux-musl"
      - name: Process and Package
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        env:
          SOURCE_TAG: ${{ steps.config.outputs.SOURCE_TAG }}
          TARGET_NAME: ${{ steps.config.outputs.TARGET_NAME }}
        run: echo SOURCE_TAG ${SOURCE_TAG} && cp src/target/${TARGET_NAME}/release/dclia . && strip dclia && cp src/target/${TARGET_NAME}/release/dclic . && strip dclic  && cp src/target/${TARGET_NAME}/release/dclics . && strip dclics && cp src/target/${TARGET_NAME}/release/dclims . && strip dclims && cp src/target/${TARGET_NAME}/release/dclim . && strip dclim && cp src/target/${TARGET_NAME}/release/dclis . && strip dclis && cp src/target/${TARGET_NAME}/release/dclitime . && strip dclitime && cp src/target/${TARGET_NAME}/release/dcliah . && strip dcliah && cp src/target/${TARGET_NAME}/release/dclias . && strip dclias && zip -j dcli_${TARGET_NAME}_${SOURCE_TAG}.zip RELEASE.md README.md LICENSE.md dclia dclic dclics dclims dclim dclis dclitime dcliah dclias
        
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dcli_${{ steps.config.outputs.TARGET_NAME }}_${{ steps.config.outputs.SOURCE_TAG }}.zip
            RELEASE.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows-msvc:
    runs-on: windows-latest
    steps:

      #set some environement variables that we can use through the rest of our
      #action
      - name: Setup Config
        id: config
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=TARGET_NAME::x86_64-pc-windows-msvc
        shell: bash

      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ steps.config.outputs.TARGET_NAME }}
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        env:
          DESTINY_API_KEY: ${{ secrets.DESTINY_API_KEY }}
          RUSTFLAGS: '-C target-feature=+crt-static'
        with:
          use-cross: true
          command: build
          args: --manifest-path=src/Cargo.toml --release --target ${{ steps.config.outputs.TARGET_NAME }}
      - name: Process
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        env:
          SOURCE_TAG: ${{ steps.config.outputs.SOURCE_TAG }}
          TARGET_NAME: ${{ steps.config.outputs.TARGET_NAME }}
        run: echo SOURCE_TAG ${SOURCE_TAG} && cp src/target/${TARGET_NAME}/release/dclia.exe . && strip dclia.exe && cp src/target/${TARGET_NAME}/release/dclic.exe . && strip dclic.exe  && cp src/target/${TARGET_NAME}/release/dclics.exe . && strip dclics.exe && cp src/target/${TARGET_NAME}/release/dclims.exe . && strip dclims.exe && cp src/target/${TARGET_NAME}/release/dclim.exe . && strip dclim.exe && cp src/target/${TARGET_NAME}/release/dclis.exe . && strip dclis.exe && cp src/target/${TARGET_NAME}/release/dclitime.exe . && strip dclitime.exe && cp src/target/${TARGET_NAME}/release/dcliah.exe . && strip dcliah.exe && cp src/target/${TARGET_NAME}/release/dclias.exe . && strip dclias.exe
        shell: bash
      - name: Package
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        run: Compress-Archive -Path RELEASE.md, README.md, LICENSE.md, dclia.exe, dclic.exe, dclics.exe, dclim.exe, dclims.exe, dclis.exe, dclitime.exe, dcliah.exe, dclias.exe -DestinationPath dcli_${{ steps.config.outputs.TARGET_NAME }}_${{ steps.config.outputs.SOURCE_TAG }}.zip -CompressionLevel Optimal
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dcli_${{ steps.config.outputs.TARGET_NAME }}_${{ steps.config.outputs.SOURCE_TAG }}.zip
            RELEASE.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac-x86_64:
    runs-on: macos-10.15
    steps:

      #set some environement variables that we can use through the rest of our
      #action
      - name: Setup Config
        id: config
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=TARGET_NAME::x86_64-apple-darwin

      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ steps.config.outputs.TARGET_NAME }}
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        env:
          DESTINY_API_KEY: ${{ secrets.DESTINY_API_KEY }}
        with:
          use-cross: true
          command: build
          args: --manifest-path=src/Cargo.toml --release --target ${{ steps.config.outputs.TARGET_NAME }}
      - name: Process
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        env:
          SOURCE_TAG: ${{ steps.config.outputs.SOURCE_TAG }}
          TARGET_NAME: ${{ steps.config.outputs.TARGET_NAME }}
          DESTINY_API_KEY: ${{ secrets.DESTINY_API_KEY }}
        run: echo SOURCE_TAG ${SOURCE_TAG} && cp src/target/${TARGET_NAME}/release/dclia . && strip dclia && cp src/target/${TARGET_NAME}/release/dclic . && strip dclic  && cp src/target/${TARGET_NAME}/release/dclics . && strip dclics && cp src/target/${TARGET_NAME}/release/dclims . && strip dclims && cp src/target/${TARGET_NAME}/release/dclim . && strip dclim && cp src/target/${TARGET_NAME}/release/dclis . && strip dclis && cp src/target/${TARGET_NAME}/release/dclitime . && strip dclitime && codesign -s - dclitime && cp src/target/${TARGET_NAME}/release/dcliah . && strip dcliah && cp src/target/${TARGET_NAME}/release/dclias . && strip dclias && zip -j dcli_${TARGET_NAME}_${SOURCE_TAG}.zip RELEASE.md README.md LICENSE.md dclia dclic dclics dclims dclim dclis dclitime dcliah dclias
        
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dcli_${{ steps.config.outputs.TARGET_NAME }}_${{ steps.config.outputs.SOURCE_TAG }}.zip
            RELEASE.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
